name: release

on:
  push:
    branches:
      - main

permissions:
  pull-requests: read
  contents: write
  issues: write
  deployments: write

jobs:
  release:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      # 依存関係
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - name: build
        run: make build
      - name: Release
        id: release
        uses: softprops/action-gh-release@4634c16e79c963813287e889244c50009e7f0981
        with:
          generate_release_notes: false
          target_commitish: "main"
          files: |
            bin/*
